<?php
// header.php - Main Navigation with Notification Badges
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database connection for notifications
$unread_count = 0;
$user_unread_count = 0;
if (!isset($conn)) {
    $conn = null;
}

if (isset($_SESSION['user_id'])) {
    // Include database connection
    include_once('includes/db.php');
    
    // Check if connection is valid before using it
    if (isset($conn) && $conn && !is_bool($conn)) {
        // Get unread message count for admin/owner (for the bell icon)
        if (isset($_SESSION['role']) && ($_SESSION['role'] == 'admin' || $_SESSION['role'] == 'owner')) {
            $result = mysqli_query($conn, "SELECT COUNT(*) as count FROM contact_messages WHERE status = 'unread'");
            if ($result) {
                $unread_count = mysqli_fetch_assoc($result)['count'];
            }
        }
        
        // Get user-specific unread replies (for members - when admin replied to their message)
        $user_id = $_SESSION['user_id'];
        $email_condition = isset($_SESSION['email']) ? "OR email = '{$_SESSION['email']}'" : "";
        $user_unread = mysqli_query($conn, "SELECT COUNT(*) as count FROM contact_messages WHERE (user_id = '$user_id' $email_condition) AND status = 'replied' AND admin_reply IS NOT NULL AND is_read_by_user = 0");
        if ($user_unread) {
            $user_unread_count = mysqli_fetch_assoc($user_unread)['count'];
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WallHub - Premium Wallpapers</title>
<!-- ========================================== -->
<!-- FAVICON - Generated by RealFaviconGenerator -->
<!-- ========================================== -->
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
<meta name="apple-mobile-web-app-title" content="WallHub" />
<link rel="manifest" href="/site.webmanifest" />

<!-- ========================================== -->
<!-- OPEN GRAPH / SOCIAL SHARING                -->
<!-- ========================================== -->
<meta property="og:title" content="WallHub - Premium Wallpapers">
<meta property="og:description" content="Download stunning 4K HD wallpapers from anime, movies, gaming, nature, and more. Free daily downloads.">
<meta property="og:image" content="https://wallhub.online/images/logo-og.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:url" content="https://wallhub.online">
<meta property="og:type" content="website">
<meta property="og:site_name" content="WallHub">

<!-- ========================================== -->
<!-- CSS & FONTS                                -->
<!-- ========================================== -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@900&family=DM+Sans:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/components.css">

<!-- ========================================== -->
<!-- GOOGLE ANALYTICS - CORRECT PLACEMENT      -->
<!-- ========================================== -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-966S46KZ4J"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-966S46KZ4J');
</script>

<style>
/* ========================================== */
/* RESET & NAVIGATION STYLES                 */
/* ========================================== */
#wh-nav, #wh-nav * { box-sizing: border-box !important; }
#wh-nav {
    display: block !important;
    width: 100% !important;
    position: sticky !important;
    top: 0 !important;
    z-index: 9999 !important;
    background: rgba(8,8,18,.93) !important;
    backdrop-filter: blur(20px) !important;
    -webkit-backdrop-filter: blur(20px) !important;
    border-bottom: 1px solid rgba(255,255,255,.07) !important;
    padding: 0 !important;
    margin: 0 !important;
}
#wh-nav::before {
    content: '' !important;
    position: absolute !important;
    top: 0 !important; left: 0 !important; right: 0 !important;
    height: 2px !important;
    background: linear-gradient(90deg, transparent, #ff6b35 25%, #ff4757 55%, #a855f7 80%, transparent) !important;
    z-index: 2 !important;
}

/* ========================================== */
/* NAVIGATION BAR - ONE ROW                   */
/* ========================================== */
#wh-bar {
    display: flex !important;
    flex-direction: row !important;
    flex-wrap: nowrap !important;
    align-items: center !important;
    justify-content: flex-start !important;
    width: 100% !important;
    height: 68px !important;
    padding: 0 20px !important;
    gap: 8px !important;
    position: relative !important;
    z-index: 1 !important;
    margin: 0 !important;
    list-style: none !important;
}

/* ========================================== */
/* LOGO - IMAGE VERSION                       */
/* ========================================== */
#wh-logo {
    display: flex !important;
    align-items: center !important;
    text-decoration: none !important;
    flex-shrink: 0 !important;
    gap: 12px !important;
}

#wh-logo-img {
    height: 60px !important;
    width: auto !important;
    display: block !important;
    transition: transform 0.3s ease !important;
}

#wh-logo:hover #wh-logo-img {
    transform: scale(1.05) !important;
}

#wh-tagline {
    font-family: 'DM Sans', sans-serif !important;
    font-size: 0.7rem !important;
    font-weight: 500 !important;
    color: #ffffff !important;
    letter-spacing: 0.15em !important;
    text-shadow: 0 0 20px rgba(255,255,255,0.15) !important;
    opacity: 0.9 !important;
    white-space: nowrap !important;
}

#wh-logo:hover #wh-tagline {
    opacity: 1 !important;
}

/* Hide old logo elements */
#wh-logo-icon, .wh-dot, #wh-wordmark-wrap {
    display: none !important;
}

/* ========================================== */
/* NAV LINKS                                  */
/* ========================================== */
#wh-links {
    display: flex !important;
    flex-direction: row !important;
    flex-wrap: nowrap !important;
    align-items: center !important;
    gap: 2px !important;
    flex: 1 1 auto !important;
    justify-content: center !important;
    margin: 0 !important;
    padding: 0 !important;
    list-style: none !important;
}
.wh-a {
    color: rgba(255,255,255,.58) !important;
    text-decoration: none !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: .84rem !important;
    font-weight: 500 !important;
    padding: 6px 12px !important;
    border-radius: 8px !important;
    white-space: nowrap !important;
    display: inline-flex !important;
    align-items: center !important;
    transition: color .2s, background .2s !important;
    background: transparent !important;
    border: none !important;
}
.wh-a:hover { color: #fff !important; background: rgba(255,255,255,.07) !important; }
.wh-a.active { color: #ff6b35 !important; background: rgba(255,107,53,.10) !important; }

.wh-fav {
    position: relative !important;
}
.wh-fav i {
    margin-right: 6px !important;
}
.wh-fav.active {
    color: #ff4757 !important;
    background: rgba(255,71,87,.10) !important;
}

/* ========================================== */
/* SEARCH                                     */
/* ========================================== */
#wh-search-wrap { position: relative !important; flex-shrink: 0 !important; }
#wh-pill {
    display: flex !important;
    flex-direction: row !important;
    align-items: center !important;
    background: rgba(255,255,255,.06) !important;
    border: 1px solid rgba(255,255,255,.09) !important;
    border-radius: 50px !important;
    padding: 0 5px 0 13px !important;
    gap: 7px !important;
    width: 195px !important;
    transition: width .3s, border-color .25s, box-shadow .25s !important;
    margin: 0 !important;
}
#wh-pill:focus-within {
    width: 235px !important;
    border-color: rgba(255,107,53,.45) !important;
    box-shadow: 0 0 0 3px rgba(255,107,53,.08) !important;
}
#wh-pill input {
    background: transparent !important;
    border: none !important;
    outline: none !important;
    box-shadow: none !important;
    color: #fff !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: .82rem !important;
    width: 100% !important;
    padding: 9px 0 !important;
    margin: 0 !important;
    flex: 1 !important;
}
#wh-pill input::placeholder { color: rgba(255,255,255,.28) !important; }
#wh-pill input:focus { outline: none !important; box-shadow: none !important; border: none !important; }
.wh-si { color: rgba(255,255,255,.26) !important; font-size: 11px !important; flex-shrink: 0 !important; }
.wh-go {
    background: linear-gradient(135deg,#ff6b35,#ff4757) !important;
    border: none !important;
    border-radius: 50px !important;
    width: 29px !important; height: 29px !important;
    display: flex !important; align-items: center !important; justify-content: center !important;
    color: #fff !important; font-size: 11px !important;
    cursor: pointer !important; flex-shrink: 0 !important;
    transition: transform .2s, box-shadow .2s !important;
}
.wh-go:hover { transform: scale(1.1) !important; box-shadow: 0 4px 12px rgba(255,107,53,.45) !important; }

/* SUGGESTIONS */
#wh-drop {
    position: absolute !important;
    top: calc(100% + 8px) !important;
    left: 0 !important; right: 0 !important;
    background: rgba(13,13,23,.98) !important;
    border: 1px solid rgba(255,255,255,.07) !important;
    border-radius: 14px !important;
    max-height: 370px !important;
    overflow-y: auto !important;
    display: none;
    z-index: 9000 !important;
    box-shadow: 0 18px 50px rgba(0,0,0,.65) !important;
}
.wh-sug { display:flex!important;align-items:center!important;gap:11px!important;padding:10px 13px!important;color:rgba(255,255,255,.75)!important;text-decoration:none!important;border-bottom:1px solid rgba(255,255,255,.04)!important;transition:background .15s!important;cursor:pointer!important; }
.wh-sug:hover { background:rgba(255,107,53,.09)!important;color:#fff!important; }
.wh-sug img { width:38px!important;height:38px!important;object-fit:cover!important;border-radius:7px!important; }
.wh-msg { padding:18px!important;text-align:center!important;color:rgba(255,255,255,.35)!important;font-size:.83rem!important; }
.wh-spin { animation:wh-rot .9s linear infinite!important;display:inline-block!important; }
@keyframes wh-rot{to{transform:rotate(360deg);}}

/* ========================================== */
/* CONTACT                                    */
/* ========================================== */
#wh-contact {
    display: flex !important; align-items: center !important; gap: 6px !important;
    color: rgba(255,255,255,.58) !important;
    text-decoration: none !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: .82rem !important; font-weight: 500 !important;
    padding: 7px 15px !important;
    border-radius: 50px !important;
    border: 1px solid rgba(255,255,255,.08) !important;
    background: rgba(255,255,255,.04) !important;
    white-space: nowrap !important;
    flex-shrink: 0 !important;
    transition: all .25s !important;
}
#wh-contact:hover { background:rgba(255,107,53,.10)!important;border-color:rgba(255,107,53,.28)!important;color:#ff8a65!important; }

/* ========================================== */
/* NOTIFICATION BADGE STYLES                  */
/* ========================================== */
.msg-bell-wrapper {
    position: relative !important;
    display: flex !important;
    align-items: center !important;
    margin-right: 5px !important;
}
.msg-bell-btn {
    background: rgba(255,255,255,.05) !important;
    border: 1px solid rgba(255,255,255,.08) !important;
    border-radius: 50% !important;
    width: 36px !important;
    height: 36px !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    color: rgba(255,255,255,.7) !important;
    font-size: 1rem !important;
    cursor: pointer !important;
    transition: all .25s !important;
    position: relative !important;
    text-decoration: none !important;
}
.msg-bell-btn:hover {
    background: rgba(255,107,53,.15) !important;
    border-color: rgba(255,107,53,.4) !important;
    color: #ff8a65 !important;
}
.badge-count {
    position: absolute !important;
    top: -6px !important;
    right: -6px !important;
    background: linear-gradient(135deg, #ff4757, #e11d1d) !important;
    color: white !important;
    font-size: 0.65rem !important;
    font-weight: bold !important;
    padding: 2px 6px !important;
    border-radius: 50% !important;
    min-width: 18px !important;
    text-align: center !important;
    box-shadow: 0 0 8px rgba(225,29,29,0.5) !important;
    animation: pulse 1.5s infinite !important;
}
@keyframes pulse {
    0% { transform: scale(1); opacity: 1; }
    50% { transform: scale(1.15); opacity: 0.9; }
    100% { transform: scale(1); opacity: 1; }
}

.user-msg-badge {
    position: absolute !important;
    top: -4px !important;
    right: -4px !important;
    background: linear-gradient(135deg, #ff4757, #e11d1d) !important;
    color: white !important;
    font-size: 0.55rem !important;
    font-weight: bold !important;
    padding: 2px 5px !important;
    border-radius: 50% !important;
    min-width: 16px !important;
    text-align: center !important;
    box-shadow: 0 0 6px rgba(225,29,29,0.5) !important;
    animation: pulse 1.5s infinite !important;
}

.msg-badge-dropdown {
    background: #e11d1d !important;
    color: white !important;
    padding: 2px 8px !important;
    border-radius: 20px !important;
    font-size: 0.65rem !important;
    margin-left: 8px !important;
    font-weight: bold !important;
}

/* ========================================== */
/* USER AREA                                  */
/* ========================================== */
#wh-user { display:flex!important;align-items:center!important;gap:8px!important;flex-shrink:0!important;margin-left:4px!important; }
.wh-utrig {
    display: flex !important; align-items: center !important; gap: 8px !important;
    background: rgba(255,255,255,.05) !important;
    border: 1px solid rgba(255,255,255,.10) !important;
    border-radius: 50px !important;
    padding: 5px 14px 5px 6px !important;
    color: #fff !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: .83rem !important; font-weight: 500 !important;
    cursor: pointer !important; white-space: nowrap !important;
    transition: background .25s, border-color .25s !important;
    position: relative !important;
}
.wh-utrig:hover { background:rgba(255,255,255,.09)!important;border-color:rgba(255,255,255,.18)!important; }
.wh-av { width:28px!important;height:28px!important;border-radius:50%!important;background:linear-gradient(135deg,#ff6b35,#a855f7)!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:11px!important;color:#fff!important;flex-shrink:0!important;position:relative!important; }
.wh-bdg { font-size:.57rem!important;font-weight:700!important;padding:2px 8px!important;border-radius:20px!important;letter-spacing:.05em!important; }
.wh-p { background:linear-gradient(90deg,#ffd700,#ffb800)!important;color:#6a3c00!important; }
.wh-adm { background:linear-gradient(90deg,#ff4757,#e11d1d)!important;color:#fff!important; }
.wh-owner { background: linear-gradient(135deg, #FFD700, #FF8C00) !important; color: #000 !important; box-shadow: 0 0 10px rgba(255,215,0,0.5); }
.wh-chv { font-size:9px!important;color:rgba(255,255,255,.30)!important;transition:transform .25s!important; }

/* DROPDOWN PANEL */
.wh-dm {
    position: absolute !important;
    top: calc(100% + 10px) !important;
    right: 0 !important;
    min-width: 220px !important;
    background: rgba(12,12,22,.98) !important;
    border: 1px solid rgba(255,255,255,.08) !important;
    border-radius: 15px !important;
    padding: 7px !important;
    display: none;
    z-index: 9999 !important;
    box-shadow: 0 20px 60px rgba(0,0,0,.7) !important;
}
.wh-dm.open { display: block !important; animation: wh-fd .18s ease !important; }
@keyframes wh-fd { from{opacity:0;transform:translateY(-6px);}to{opacity:1;transform:translateY(0);} }
.wh-dh { font-size:.67rem!important;color:rgba(255,255,255,.22)!important;font-weight:600!important;letter-spacing:.09em!important;text-transform:uppercase!important;padding:7px 11px 3px!important;font-family:'DM Sans',sans-serif!important;display:block!important; }
.wh-di { display:flex!important;align-items:center!important;gap:10px!important;padding:9px 11px!important;border-radius:9px!important;color:rgba(255,255,255,.68)!important;text-decoration:none!important;font-family:'DM Sans',sans-serif!important;font-size:.83rem!important;font-weight:400!important;transition:background .15s,color .15s!important;background:transparent!important; }
.wh-di i { width:14px!important;font-size:12px!important;color:rgba(255,255,255,.27)!important;transition:color .15s!important; }
.wh-di:hover { background:rgba(255,255,255,.06)!important;color:#fff!important; }
.wh-di:hover i { color:#ff6b35!important; }
.wh-di.wh-out { color:rgba(255,90,90,.72)!important; }
.wh-di.wh-out:hover { background:rgba(255,71,87,.07)!important;color:#ff7070!important; }
.wh-sep { border:none!important;border-top:1px solid rgba(255,255,255,.05)!important;margin:4px 0!important; }

/* AUTH BUTTONS */
.wh-ln { display:inline-flex!important;align-items:center!important;gap:6px!important;padding:7px 16px!important;border-radius:50px!important;border:1px solid rgba(255,107,53,.35)!important;background:transparent!important;color:#ff8a65!important;text-decoration:none!important;font-family:'DM Sans',sans-serif!important;font-size:.81rem!important;font-weight:500!important;white-space:nowrap!important;transition:all .25s!important; }
.wh-ln:hover { border-color:#ff6b35!important;background:rgba(255,107,53,.09)!important;color:#ff6b35!important; }
.wh-su { display:inline-flex!important;align-items:center!important;gap:6px!important;padding:7px 18px!important;border-radius:50px!important;border:none!important;background:linear-gradient(135deg,#ff6b35,#ff4757)!important;color:#fff!important;text-decoration:none!important;font-family:'DM Sans',sans-serif!important;font-size:.81rem!important;font-weight:600!important;white-space:nowrap!important;box-shadow:0 4px 14px rgba(255,107,53,.28)!important;transition:transform .25s,box-shadow .25s!important; }
.wh-su:hover { transform:translateY(-1px)!important;box-shadow:0 7px 22px rgba(255,107,53,.45)!important;color:#fff!important; }

/* MOBILE HAMBURGER */
#wh-ham { display:none!important;background:rgba(255,255,255,.06)!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:9px!important;padding:7px 10px!important;cursor:pointer!important;color:rgba(255,255,255,.75)!important;font-size:15px!important;flex-shrink:0!important; }

/* MOBILE DRAWER */
#wh-drawer { display:none;flex-direction:column;gap:8px;padding:12px 18px 16px;border-top:1px solid rgba(255,255,255,.05); }
#wh-drawer.open { display:flex!important; }

#wh-pill-m {
    display: flex !important;
    align-items: center !important;
    background: rgba(255,255,255,.06) !important;
    border: 1px solid rgba(255,255,255,.09) !important;
    border-radius: 50px !important;
    padding: 0 5px 0 13px !important;
    gap: 7px !important;
    width: 100% !important;
}
#wh-pill-m input {
    background: transparent !important;
    border: none !important;
    outline: none !important;
    color: #fff !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: .82rem !important;
    width: 100% !important;
    padding: 9px 0 !important;
}

/* RESPONSIVE */
@media(max-width:900px){
    #wh-links, #wh-search-wrap, #wh-contact { display:none!important; }
    #wh-ham { display:block!important; }
    #wh-bar { justify-content:space-between!important; }
}
</style>
</head>
<body>

<?php include('popup.php'); ?>

<nav id="wh-nav">
  <div id="wh-bar">

    <!-- ========================================== -->
    <!-- LOGO - IMAGE VERSION WITH TAGLINE           -->
    <!-- ========================================== -->
    <a id="wh-logo" href="index">
        <img src="/images/aaaaa.png" 
             alt="WallHub - Premium Wallpapers" 
             id="wh-logo-img">
        
    </a>

    <!-- NAV LINKS -->
    <div id="wh-links">
      <a class="wh-a" href="index">Home</a>
      <a class="wh-a" href="categories">Categories</a>
      <a class="wh-a" href="trending">Trending</a>
      <a class="wh-a" href="popular-collections">Collections</a>
      <a class="wh-a wh-fav" href="favorites">
        <i class="fas fa-heart"></i> Favorites
      </a>
    </div>

    <!-- SEARCH -->
    <div id="wh-search-wrap">
      <form action="search" method="GET" autocomplete="off" style="margin:0;padding:0;">
        <div id="wh-pill">
          <i class="fas fa-search wh-si"></i>
          <input type="text" name="q" id="wh-q"
                 placeholder="Search wallpapers&hellip;"
                 value="<?php echo isset($_GET['q']) ? htmlspecialchars($_GET['q']) : ''; ?>"
                 autocomplete="off">
          <button class="wh-go" type="submit"><i class="fas fa-arrow-right"></i></button>
        </div>
      </form>
      <div id="wh-drop"></div>
    </div>

    <!-- CONTACT -->
    <a id="wh-contact" href="contact">
      <i class="fas fa-paper-plane" style="font-size:10px;"></i> Contact
    </a>

    <!-- USER AREA WITH NOTIFICATION BADGES -->
    <div id="wh-user">
      <?php if (isset($_SESSION['user_id'])): ?>
        
        <!-- MESSAGE BELL FOR ADMIN/OWNER -->
        <?php if (isset($_SESSION['role']) && ($_SESSION['role'] == 'admin' || $_SESSION['role'] == 'owner')): ?>
          <div class="msg-bell-wrapper">
            <a href="admin_messages" class="msg-bell-btn">
              <i class="fas fa-bell"></i>
              <?php if($unread_count > 0): ?>
                <span class="badge-count"><?php echo $unread_count; ?></span>
              <?php endif; ?>
            </a>
          </div>
        <?php endif; ?>
        
        <!-- USER AVATAR / DROPDOWN TRIGGER -->
        <div style="position:relative;">
          <button class="wh-utrig" id="wh-utrig" onclick="whToggle()">
            <div class="wh-av">
              <i class="fas fa-user"></i>
              <?php if($user_unread_count > 0): ?>
                <span class="user-msg-badge"><?php echo $user_unread_count; ?></span>
              <?php endif; ?>
            </div>
            <span><?php echo htmlspecialchars($_SESSION['username'] ?? 'User'); ?></span>
            <?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'owner'): ?>
              <span class="wh-bdg wh-owner">👑 OWNER</span>
            <?php elseif (isset($_SESSION['role']) && $_SESSION['role'] === 'admin'): ?>
              <span class="wh-bdg wh-adm">ADMIN</span>
            <?php elseif (isset($_SESSION['role']) && $_SESSION['role'] === 'premium'): ?>
              <span class="wh-bdg wh-p">PREMIUM</span>
            <?php endif; ?>
            <i class="fas fa-chevron-down wh-chv" id="wh-chv"></i>
          </button>
          
          <!-- DROPDOWN MENU -->
          <div class="wh-dm" id="wh-dm">
            <span class="wh-dh">Account</span>
            <a class="wh-di" href="profile"><i class="fas fa-user"></i> My Profile</a>
            <a class="wh-di" href="my-downloads"><i class="fas fa-download"></i> My Downloads</a>
            <a class="wh-di" href="favorites"><i class="fas fa-heart"></i> My Favorites</a>
            <a class="wh-di" href="my_messages">
              <i class="fas fa-inbox"></i> My Messages
              <?php if($user_unread_count > 0): ?>
                <span class="msg-badge-dropdown"><?php echo $user_unread_count; ?> new</span>
              <?php endif; ?>
            </a>
            <a class="wh-di" href="contact"><i class="fas fa-envelope"></i> Contact Support</a>
            
            <?php if (isset($_SESSION['role']) && ($_SESSION['role'] === 'admin' || $_SESSION['role'] === 'owner')): ?>
              <hr class="wh-sep">
              <span class="wh-dh">Admin</span>
              <a class="wh-di" href="admin"><i class="fas fa-crown"></i> Admin Panel</a>
              <a class="wh-di" href="admin_messages">
                <i class="fas fa-envelope"></i> Messages
                <?php if($unread_count > 0): ?>
                  <span class="msg-badge-dropdown"><?php echo $unread_count; ?> unread</span>
                <?php endif; ?>
              </a>
              <a class="wh-di" href="add"><i class="fas fa-plus-circle"></i> Add Desktop Wallpaper</a>
              <a class="wh-di" href="upload_mobile"><i class="fas fa-plus-circle"></i> Add Mobile Wallpaper</a>
            <?php endif; ?>
            
            <hr class="wh-sep">
            <a class="wh-di wh-out" href="logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </div>
        </div>
        
      <?php else: ?>
        <a class="wh-ln" href="login"><i class="fas fa-user-circle" style="font-size:12px;"></i> Login</a>
        <a class="wh-su" href="register"><i class="fas fa-rocket" style="font-size:11px;"></i> Sign Up</a>
      <?php endif; ?>
    </div>
    
    <!-- HAMBURGER (mobile only) -->
    <button id="wh-ham" onclick="whDrawer()" aria-label="Menu">
      <i class="fas fa-bars" id="wh-ham-icon"></i>
    </button>

  </div><!-- /#wh-bar -->

  <!-- MOBILE DRAWER -->
  <div id="wh-drawer">
    <a class="wh-a" href="index">Home</a>
    <a class="wh-a" href="categories">Categories</a>
    <a class="wh-a" href="trending">Trending</a>
    <a class="wh-a" href="popular-collections">Collections</a>
    <a class="wh-a wh-fav" href="favorites">
      <i class="fas fa-heart"></i> Favorites
    </a>
    <form action="search" method="GET" autocomplete="off" style="margin:0;padding:0;">
      <div id="wh-pill-m">
        <i class="fas fa-search wh-si"></i>
        <input type="text" name="q" placeholder="Search wallpapers&hellip;"
               value="<?php echo isset($_GET['q']) ? htmlspecialchars($_GET['q']) : ''; ?>"
               autocomplete="off">
        <button class="wh-go" type="submit"><i class="fas fa-arrow-right"></i></button>
      </div>
    </form>
    <a id="wh-contact" href="contact" style="justify-content:center;">
      <i class="fas fa-paper-plane" style="font-size:10px;"></i> Contact
    </a>
  </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
(function(){
  // Active link
  var page = window.location.pathname.split('/').pop() || 'index';
  document.querySelectorAll('.wh-a').forEach(function(a){
    if(a.getAttribute('href') === page) a.classList.add('active');
  });

  // User dropdown
  window.whToggle = function(){
    var dm  = document.getElementById('wh-dm');
    var chv = document.getElementById('wh-chv');
    if(!dm) return;
    var open = dm.classList.toggle('open');
    if(chv) chv.style.transform = open ? 'rotate(180deg)' : '';
  };
  document.addEventListener('click', function(e){
    var trig = document.getElementById('wh-utrig');
    var dm   = document.getElementById('wh-dm');
    if(!dm || !trig) return;
    if(!trig.contains(e.target) && !dm.contains(e.target)){
      dm.classList.remove('open');
      var chv = document.getElementById('wh-chv');
      if(chv) chv.style.transform = '';
    }
  });

  // Mobile drawer
  window.whDrawer = function(){
    var d    = document.getElementById('wh-drawer');
    var icon = document.getElementById('wh-ham-icon');
    if(!d) return;
    var open = d.classList.toggle('open');
    if(icon) icon.className = open ? 'fas fa-times' : 'fas fa-bars';
  };

  // Live search
  var inp  = document.getElementById('wh-q');
  var drop = document.getElementById('wh-drop');
  var tmr, hlIdx = -1;
  if(inp && drop){
    inp.addEventListener('input', function(){
      clearTimeout(tmr);
      var q = this.value.trim();
      if(q.length < 2){ drop.style.display='none'; return; }
      tmr = setTimeout(function(){ loadSug(q); }, 280);
    });
    inp.addEventListener('keydown', function(e){
      var rows = drop.querySelectorAll('.wh-sug');
      if(!rows.length) return;
      if(e.key==='ArrowDown'){ e.preventDefault(); hlIdx=Math.min(hlIdx+1,rows.length-1); hl(rows); }
      else if(e.key==='ArrowUp'){ e.preventDefault(); hlIdx=Math.max(hlIdx-1,-1); hl(rows); }
      else if(e.key==='Enter' && hlIdx>=0){ e.preventDefault(); window.location.href=rows[hlIdx].href; }
      else if(e.key==='Escape'){ drop.style.display='none'; }
    });
    document.addEventListener('click', function(e){
      if(!inp.contains(e.target) && !drop.contains(e.target)) drop.style.display='none';
    });
  }
  function hl(rows){
    rows.forEach(function(r,i){
      r.style.background = i===hlIdx ? 'rgba(255,107,53,.12)' : '';
      if(i===hlIdx) r.scrollIntoView({block:'nearest'});
    });
  }
  function loadSug(q){
    drop.innerHTML = '<div class="wh-msg"><i class="fas fa-spinner wh-spin"></i> Searching\u2026</div>';
    drop.style.display = 'block';
    fetch('search_ajax.php?q='+encodeURIComponent(q))
      .then(function(r){ return r.text(); })
      .then(function(html){
        var d = document.createElement('div'); d.textContent = q;
        drop.innerHTML = html.trim()
          ? html
          : '<div class="wh-msg">No results for \u201c'+d.innerHTML+'\u201d</div>';
        drop.style.display = 'block';
        hlIdx = -1;
      })
      .catch(function(){ drop.innerHTML='<div class="wh-msg">Could not load results</div>'; });
  }
})();

// ============================================
// REAL-TIME NOTIFICATION CHECK
// ============================================
function checkNewMessages() {
    fetch('check_notifications')
        .then(response => response.json())
        .then(data => {
            // Update admin bell badge
            if (data.admin_unread > 0) {
                const bellBadge = document.querySelector('.msg-bell-btn .badge-count');
                if (bellBadge) {
                    bellBadge.textContent = data.admin_unread;
                    bellBadge.style.display = 'block';
                } else {
                    const bellBtn = document.querySelector('.msg-bell-btn');
                    if (bellBtn && !bellBtn.querySelector('.badge-count')) {
                        const newBadge = document.createElement('span');
                        newBadge.className = 'badge-count';
                        newBadge.textContent = data.admin_unread;
                        bellBtn.appendChild(newBadge);
                    }
                }
            } else {
                const bellBadge = document.querySelector('.msg-bell-btn .badge-count');
                if (bellBadge) {
                    bellBadge.style.display = 'none';
                }
            }
            
            // Update user avatar badge
            if (data.user_unread > 0) {
                const userBadge = document.querySelector('.user-msg-badge');
                if (userBadge) {
                    userBadge.textContent = data.user_unread;
                    userBadge.style.display = 'flex';
                } else {
                    const userAvatar = document.querySelector('.wh-av');
                    if (userAvatar && !userAvatar.querySelector('.user-msg-badge')) {
                        const newBadge = document.createElement('span');
                        newBadge.className = 'user-msg-badge';
                        newBadge.textContent = data.user_unread;
                        userAvatar.style.position = 'relative';
                        userAvatar.appendChild(newBadge);
                    }
                }
                
                const dropdownBadge = document.querySelector('.wh-di[href="my_messages"] .msg-badge-dropdown');
                if (dropdownBadge) {
                    dropdownBadge.textContent = data.user_unread + ' new';
                }
            } else {
                const userBadge = document.querySelector('.user-msg-badge');
                if (userBadge) {
                    userBadge.style.display = 'none';
                }
                const dropdownBadge = document.querySelector('.wh-di[href="my_messages"] .msg-badge-dropdown');
                if (dropdownBadge) {
                    dropdownBadge.remove();
                }
            }
        })
        .catch(err => console.log('Notification check error:', err));
}

// Check for new messages every 30 seconds
setInterval(checkNewMessages, 30000);

// Also check immediately when page loads
document.addEventListener('DOMContentLoaded', function() {
    checkNewMessages();
});
</script>
</body>
</html>
